export const IPC_CHANNELS = {
  GET_CONFIGS_CHANNEL: 'GET_CONFIGS_CHANNEL',
  PUSH_CONFIGS_CHANNEL: 'PUSH_CONFIGS_CHANNEL',
  ONE_COMME_BOOT_REQUEST_CHANNEL: 'ONE_COMME_BOOT_REQUEST_CHANNEL',
  RESET_CONFIGS_REQUEST_CHANNEL: 'RESET_CONFIGS_REQUEST_CHANNEL',
  REQUEST_HIDE_COMMENT_CHANNEL: 'REQUEST_HIDE_COMMENT_CHANNEL',
} as const;
