name: 'CI'

on:
  pull_request:
    branches: [develop, master]

jobs:
  lint:
    name: Lint
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Review ESLint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src/'
          fail_on_error: true

  test:
    name: Test
    timeout-minutes: 3
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install package
        run: npm ci
      - name: Run Jest
        run: npm run jest -- --json --outputFile="jest.results.json"
      - name: Show test result
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'npm run jest'
