name: 'CD(delivery)'

on:
  pull_request:
    branches: [develop, master]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install package
        run: |
          npm ci
      - name: Build production
        run: npm run production
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cleanup artifacts
        run: npx rimraf "dist/!(*.exe)"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: dist
