name: Jest

on:
  pull_request:
    branches: [develop, master]

jobs:
  build:
    name: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Show annotations and coverage
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }'
        with:
          test-command: 'npm run jest'
