name: 'Jest'

on:
  pull_request:
    branches: [develop, master]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install package
        run: npm ci
      - name: Run Jest
        run: npx jest --coverage --json --outputFile="jest.results.json"
      - name: Show test result
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'npm run jest -- --coverage --json --outputFile="jest.results.json'
